python 1d_reaction_region_optimization.py --model PINN --device 'auto'
python 1d_reaction_region_optimization.py --model QRes --device 'auto'
python 1d_reaction_region_optimization.py --model FLS --device 'auto'
python 1d_reaction_region_optimization.py --model KAN --device 'auto'
python 1d_reaction_region_optimization.py --model PINNsFormer --device 'auto'