python 1d_wave_region_optimization.py --model PINN --device 'auto'
python 1d_wave_region_optimization.py --model QRes --device 'auto'
python 1d_wave_region_optimization.py --model FLS --device 'auto'
python 1d_wave_region_optimization.py --model KAN --device 'auto'
python 1d_wave_region_optimization.py --model PINNsFormer_Enc_Only --device 'auto'