python convection_point_optimization.py --model PINN --device 'auto'
python convection_point_optimization.py --model QRes --device 'auto'
python convection_point_optimization.py --model FLS --device 'auto'
python convection_point_optimization.py --model KAN --device 'auto'
python convection_point_optimization.py --model PINNsFormer --device 'auto'